name = "TorelliTrees"
uuid = "53f75a04-de99-4e46-bcd1-b171d6e83233"
authors = ["Daniel Holmes <daniel.holmes@ist.ac.at>"]
version = "1.0.0-DEV"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Karnak = "cd156443-31ad-4f6f-850f-a93ee5f75905"
Oscar = "f1435218-dba5-11e9-1e4d-f1a5fab5fc13"

[compat]
Colors = "0.13.1"
Combinatorics = "1.0.3"
Graphs = "1.13.1"
Karnak = "1.2.0"
Oscar = "1.4.1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
